/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/auth/change-password': RouteRecordInfo<'/auth/change-password', '/auth/change-password', Record<never, never>, Record<never, never>>,
    '/auth/login': RouteRecordInfo<'/auth/login', '/auth/login', Record<never, never>, Record<never, never>>,
    '/clock/time-records': RouteRecordInfo<'/clock/time-records', '/clock/time-records', Record<never, never>, Record<never, never>>,
    '/clock/timeclock': RouteRecordInfo<'/clock/timeclock', '/clock/timeclock', Record<never, never>, Record<never, never>>,
    '/employee/create': RouteRecordInfo<'/employee/create', '/employee/create', Record<never, never>, Record<never, never>>,
    '/employee/employees': RouteRecordInfo<'/employee/employees', '/employee/employees', Record<never, never>, Record<never, never>>,
    '/report/reports': RouteRecordInfo<'/report/reports', '/report/reports', Record<never, never>, Record<never, never>>,
  }
}
