/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/funcionarios': RouteRecordInfo<'/funcionarios', '/funcionarios', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/ponto': RouteRecordInfo<'/ponto', '/ponto', Record<never, never>, Record<never, never>>,
    '/pontos-registrados': RouteRecordInfo<'/pontos-registrados', '/pontos-registrados', Record<never, never>, Record<never, never>>,
    '/relatorios': RouteRecordInfo<'/relatorios', '/relatorios', Record<never, never>, Record<never, never>>,
    '/trocar-senha': RouteRecordInfo<'/trocar-senha', '/trocar-senha', Record<never, never>, Record<never, never>>,
  }
}
